"""
Django settings for jkr project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, True),
    IS_PRODUCTION=(bool, False),
)
# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-build-placeholder-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    'admin.creativegradientz.com', 
    'creativegradientz.com', 
    '.vercel.app',  # Added this to allow any Vercel subdomain
    'localhost', 
    '127.0.0.1'
])

CSRF_TRUSTED_ORIGINS = [
    'https://admin.creativegradientz.com',
    'https://creativegradientz.com',
    'https://*.vercel.app'  # Added this for secure form submission on Vercel
]



# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',

    # Third-party apps
    'ckeditor',
    'ckeditor_uploader',
    'import_export',

    # Custom apps
    'core',
    'products',
    'orders',
    'sliders',
    'pages',
    'contact',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # For static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ── Security Hardening ────────────────────────────────────────────────────────
# https://docs.djangoproject.com/en/6.0/ref/settings/#security

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN' # Allow same-origin for admin iframes (jazzmin/ckeditor)

# Enable strict SSL security if in production
IS_PRODUCTION = env('IS_PRODUCTION')
if IS_PRODUCTION:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000 # 1 Year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Ensure site isn't indexed by search engines during staging (optional)
    # DEBUG = False # Handled by env('DEBUG')


ROOT_URLCONF = 'jkr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings', # Global access to settings
                'orders.context_processors.cart_count', # New Cart Counter
            ],
        },
    },
]

WSGI_APPLICATION = 'jkr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if env('DATABASE_URL', default=''):
    DATABASES = {
        'default': env.db()
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dubai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

# Jazzmin Admin Theme Configuration
JAZZMIN_SETTINGS = {
    "site_title": "JKR International Admin",
    "site_header": "JKR Admin",
    "site_brand": "JKR Joy, Knowhow, Responsibility",
    "site_logo": "assets/logo.png",
    "welcome_sign": "Welcome to JKR Management System",
    "search_model": ["products.Product", "blog.Post"],
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "order_with_respect_to": [
        "products", 
        "orders", 
        "core", 
        "pages", 
        "contact", 
        "blog", 
        "sliders", 
        "auth"
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "products.Product": "fas fa-box-open",
        "products.Category": "fas fa-tags",
        "products.ProductSKU": "fas fa-barcode",
        "orders.CustomerOrder": "fas fa-shopping-basket",
        "core.SiteSettings": "fas fa-cogs",
        "pages.Page": "fas fa-file-alt",
        "contact.QuoteEnquiry": "fas fa-envelope-open-text",
        "blog.Post": "fas fa-newspaper",
        "sliders.Slider": "fas fa-images",
    },
}

# Loaded at top of file

STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='sk_test_12345')
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY', default='pk_test_12345')

import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
  cloud_name = env('CLOUDINARY_CLOUD_NAME', default='dltest'),
  api_key = env('CLOUDINARY_API_KEY', default='1234567'),
  api_secret = env('CLOUDINARY_API_SECRET', default='secretkey')
)


# ── Notification and Site Configuration ───────────────────────────────────────
SITE_URL = env('SITE_URL', default='http://localhost:8000')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=env('EMAIL_HOST_USER', default='notifications@jkrinternational.com'))
CURRENCY = env('CURRENCY', default='AED')

# Email Delivery (SMTP)
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com') 
EMAIL_PORT = env('EMAIL_PORT', cast=int, default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', cast=bool, default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
