# Generated by Django 6.0.3 on 2026-04-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packaging', 'Packaging'), ('ready_for_shipment', 'Ready for shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_to_origin', 'Return to origin'), ('refund', 'Refund')], default='pending', max_length=30, verbose_name='Order Status'),
        ),
    ]
