# Generated by Django 6.0.3 on 2026-04-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_customerorder_shipping_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='customerorderitem',
            name='shipping_charge',
        ),
    ]
