# Generated by Django 6.0.3 on 2026-04-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_customerorder_shipping_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total shipping cost for this order', max_digits=10),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost for this specific item', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grand Total (Items + Shipping)', max_digits=12),
        ),
    ]
