# Generated by Django 6.0.3 on 2026-04-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_collection_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='attribute_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.attributeoption', verbose_name='Value Option'),
        ),
    ]
