# Generated by Django 6.0.3 on 2026-04-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_productattributevalue_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute_option',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
